# Generated by Django 4.0.4 on 2022-05-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='rooms',
        ),
    ]
